var svgMapDataGPD = {
	data: {
	  visited: {
		  name: 'Visited? ',
		  format: "{0}",
		  thresholdMax: "YES",
		  thresholdMin: "NO"
	  },
	  date: {
		name: 'Date:',
		format: '{0}',
		
	  },
	  description: {
		name: 'Review:',
		format: '{0}',
		
	  }
	  
	},
	applyData: 'visited',
	values: {
	  AF: {visited: "No", date: "-", description: "-"},
	  AL: {visited: "No", date: "-", description: "-"},
	  DZ: {visited: "No", date: "-", description: "-"},
	  AO: {visited: "No", date: "-", description: "-"},
	  AG: {visited: "No", date: "-", description: "-"},
	  AR: {visited: "No", date: "-", description: "-"},
	  AM: {visited: "No", date: "-", description: "-"},
	  AU: {visited: "YES", date: "-", description: "-"},
	  AT: {visited: "No", date: "-", description: "-"},
	  AZ: {visited: "No", date: "-", description: "-"},
	  BS: {visited: "No", date: "-", description: "-"},
	  BH: {visited: "No", date: "-", description: "-"},
	  BD: {visited: "No", date: "-", description: "-"},
	  BB: {visited: "No", date: "-", description: "-"},
	  BY: {visited: "No", date: "-", description: "-"},
	  BE: {visited: "No", date: "-", description: "-"},
	  BZ: {visited: "No", date: "-", description: "-"},
	  BJ: {visited: "No", date: "-", description: "-"},
	  BT: {visited: "No", date: "-", description: "-"},
	  BO: {visited: "No", date: "-", description: "-"},
	  BA: {visited: "No", date: "-", description: "-"},
	  BW: {visited: "No", date: "-", description: "-"},
	  BR: {visited: "No", date: "-", description: "-"},
	  BN: {visited: "No", date: "-", description: "-"},
	  BG: {visited: "No", date: "-", description: "-"},
	  BF: {visited: "No", date: "-", description: "-"},
	  BI: {visited: "No", date: "-", description: "-"},
	  KH: {visited: "No", date: "-", description: "-"},
	  CM: {visited: "No", date: "-", description: "-"},
	  CA: {visited: "No", date: "-", description: "-"},
	  XK: {visited: "No", date: "-", description: "-"},
	  CV: {visited: "No", date: "-", description: "-"},
	  CF: {visited: "No", date: "-", description: "-"},
	  TD: {visited: "No", date: "-", description: "-"},
	  CL: {visited: "No", date: "-", description: "-"},
	  CN: {visited: "No", date: "-", description: "-"},
	  CO: {visited: "No", date: "-", description: "-"},
	  KM: {visited: "No", date: "-", description: "-"},
	  CG: {visited: "No", date: "-", description: "-"},
	  CR: {visited: "No", date: "-", description: "-"},
	  HR: {visited: "No", date: "-", description: "-"},
	  CY: {visited: "No", date: "-", description: "-"},
	  CZ: {visited: "No", date: "-", description: "-"},
	  CD: {visited: "No", date: "-", description: "-"},
	  DK: {visited: "No", date: "-", description: "-"},
	  DJ: {visited: "No", date: "-", description: "-"},
	  DM: {visited: "No", date: "-", description: "-"},
	  DO: {visited: "No", date: "-", description: "-"},
	  EC: {visited: "No", date: "-", description: "-"},
	  EG: {visited: "No", date: "-", description: "-"},
	  SV: {visited: "No", date: "-", description: "-"},
	  GQ: {visited: "No", date: "-", description: "-"},
	  ER: {visited: "No", date: "-", description: "-"},
	  EE: {visited: "No", date: "-", description: "-"},
	  ET: {visited: "No", date: "-", description: "-"},
	  FM: {visited: "No", date: "-", description: "-"},
	  FJ: {visited: "No", date: "-", description: "-"},
	  FI: {visited: "No", date: "-", description: "-"},
	  FR: {visited: "No", date: "-", description: "-"},
	  GA: {visited: "No", date: "-", description: "-"},
	  GM: {visited: "No", date: "-", description: "-"},
	  GE: {visited: "No", date: "-", description: "-"},
	  DE: {visited: "No", date: "-", description: "-"},
	  GH: {visited: "No", date: "-", description: "-"},
	  GR: {visited: "No", date: "-", description: "-"},
	  GD: {visited: "No", date: "-", description: "-"},
	  GT: {visited: "No", date: "-", description: "-"},
	  GN: {visited: "No", date: "-", description: "-"},
	  GW: {visited: "No", date: "-", description: "-"},
	  GY: {visited: "No", date: "-", description: "-"},
	  HT: {visited: "No", date: "-", description: "-"},
	  HN: {visited: "No", date: "-", description: "-"},
	  HK: {visited: "No", date: "-", description: "-"},
	  HU: {visited: "No", date: "-", description: "-"},
	  IS: {visited: "No", date: "-", description: "-"},
	  IN: {visited: "No", date: "-", description: "-"},
	  ID: {visited: "No", date: "-", description: "-"},
	  IR: {visited: "No", date: "-", description: "-"},
	  IQ: {visited: "No", date: "-", description: "-"},
	  IE: {visited: "No", date: "-", description: "-"},
	  IL: {visited: "No", date: "-", description: "-"},
	  IT: {visited: "No", date: "-", description: "-"},
	  CI: {visited: "No", date: "-", description: "-"},
	  JM: {visited: "No", date: "-", description: "-"},
	  JP: {visited: "No", date: "-", description: "-"},
	  JO: {visited: "No", date: "-", description: "-"},
	  KZ: {visited: "No", date: "-", description: "-"},
	  KE: {visited: "No", date: "-", description: "-"},
	  KI: {visited: "No", date: "-", description: "-"},
	  KW: {visited: "No", date: "-", description: "-"},
	  KG: {visited: "No", date: "-", description: "-"},
	  LA: {visited: "No", date: "-", description: "-"},
	  LV: {visited: "No", date: "-", description: "-"},
	  LB: {visited: "No", date: "-", description: "-"},
	  LS: {visited: "No", date: "-", description: "-"},
	  LR: {visited: "No", date: "-", description: "-"},
	  LY: {visited: "No", date: "-", description: "-"},
	  LT: {visited: "No", date: "-", description: "-"},
	  LU: {visited: "No", date: "-", description: "-"},
	  MO: {visited: "No", date: "-", description: "-"},
	  MK: {visited: "No", date: "-", description: "-"},
	  MG: {visited: "No", date: "-", description: "-"},
	  MW: {visited: "No", date: "-", description: "-"},
	  MY: {visited: "No", date: "-", description: "-"},
	  MV: {visited: "No", date: "-", description: "-"},
	  ML: {visited: "No", date: "-", description: "-"},
	  MT: {visited: "No", date: "-", description: "-"},
	  MH: {visited: "No", date: "-", description: "-"},
	  MR: {visited: "No", date: "-", description: "-"},
	  MU: {visited: "No", date: "-", description: "-"},
	  MX: {visited: "No", date: "-", description: "-"},
	  MD: {visited: "No", date: "-", description: "-"},
	  MN: {visited: "No", date: "-", description: "-"},
	  ME: {visited: "No", date: "-", description: "-"},
	  MA: {visited: "No", date: "-", description: "-"},
	  MZ: {visited: "No", date: "-", description: "-"},
	  MM: {visited: "No", date: "-", description: "-"},
	  NA: {visited: "No", date: "-", description: "-"},
	  NR: {visited: "No", date: "-", description: "-"},
	  NP: {visited: "No", date: "-", description: "-"},
	  NL: {visited: "No", date: "-", description: "-"},
	  NZ: {visited: "No", date: "-", description: "-"},
	  NI: {visited: "No", date: "-", description: "-"},
	  NE: {visited: "No", date: "-", description: "-"},
	  NG: {visited: "No", date: "-", description: "-"},
	  NO: {visited: "No", date: "-", description: "-"},
	  OM: {visited: "No", date: "-", description: "-"},
	  PK: {visited: "No", date: "-", description: "-"},
	  PW: {visited: "No", date: "-", description: "-"},
	  PA: {visited: "No", date: "-", description: "-"},
	  PG: {visited: "No", date: "-", description: "-"},
	  PY: {visited: "No", date: "-", description: "-"},
	  PE: {visited: "No", date: "-", description: "-"},
	  PH: {visited: "No", date: "-", description: "-"},
	  PL: {visited: "No", date: "-", description: "-"},
	  PT: {visited: "No", date: "-", description: "-"},
	  PR: {visited: "No", date: "-", description: "-"},
	  QA: {visited: "No", date: "-", description: "-"},
	  RO: {visited: "No", date: "-", description: "-"},
	  RU: {visited: "No", date: "-", description: "-"},
	  RW: {visited: "No", date: "-", description: "-"},
	  KN: {visited: "No", date: "-", description: "-"},
	  LC: {visited: "No", date: "-", description: "-"},
	  VC: {visited: "No", date: "-", description: "-"},
	  WS: {visited: "No", date: "-", description: "-"},
	  SM: {visited: "No", date: "-", description: "-"},
	  ST: {visited: "No", date: "-", description: "-"},
	  SA: {visited: "No", date: "-", description: "-"},
	  SN: {visited: "No", date: "-", description: "-"},
	  RS: {visited: "No", date: "-", description: "-"},
	  SC: {visited: "No", date: "-", description: "-"},
	  SL: {visited: "No", date: "-", description: "-"},
	  SG: {visited: "No", date: "-", description: "-"},
	  SK: {visited: "No", date: "-", description: "-"},
	  SI: {visited: "No", date: "-", description: "-"},
	  SB: {visited: "No", date: "-", description: "-"},
	  SO: {visited: "No", date: "-", description: "-"},
	  ZA: {visited: "No", date: "-", description: "-"},
	  KR: {visited: "No", date: "-", description: "-"},
	  SS: {visited: "No", date: "-", description: "-"},
	  ES: {visited: "No", date: "-", description: "-"},
	  LK: {visited: "No", date: "-", description: "-"},
	  SD: {visited: "No", date: "-", description: "-"},
	  SR: {visited: "No", date: "-", description: "-"},
	  SZ: {visited: "No", date: "-", description: "-"},
	  SE: {visited: "No", date: "-", description: "-"},
	  CH: {visited: "No", date: "-", description: "-"},
	  TW: {visited: "No", date: "-", description: "-"},
	  TJ: {visited: "No", date: "-", description: "-"},
	  TZ: {visited: "No", date: "-", description: "-"},
	  TH: {visited: "No", date: "-", description: "-"},
	  TL: {visited: "No", date: "-", description: "-"},
	  TG: {visited: "No", date: "-", description: "-"},
	  TO: {visited: "No", date: "-", description: "-"},
	  TT: {visited: "No", date: "-", description: "-"},
	  TN: {visited: "No", date: "-", description: "-"},
	  TR: {visited: "No", date: "-", description: "-"},
	  TM: {visited: "No", date: "-", description: "-"},
	  TV: {visited: "No", date: "-", description: "-"},
	  UG: {visited: "No", date: "-", description: "-"},
	  UA: {visited: "No", date: "-", description: "-"},
	  AE: {visited: "No", date: "-", description: "-"},
	  GB: {visited: "No", date: "-", description: "-"},
	  US: {visited: "No", date: "-", description: "-"},
	  UY: {visited: "No", date: "-", description: "-"},
	  UZ: {visited: "No", date: "-", description: "-"},
	  VU: {visited: "No", date: "-", description: "-"},
	  VE: {visited: "No", date: "-", description: "-"},
	  VN: {visited: "No", date: "-", description: "-"},
	  YE: {visited: "No", date: "-", description: "-"},
	  ZM: {visited: "No", date: "-", description: "-"},
	  ZW: {visited: "No", date: "-", description: "-"},
	}
  }